<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlattaPlayer.Core\PlattaPlayer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Sdk" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
